var loadBoxes = [
{name: "Special watch",
price: "$72.00",
img: "/fashion/img/photo27.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box1"},

{name: "Special",
price: "$45.00",
img: "/fashion/img/photo28.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box2"},

{name: "Special watch",
price: "$75.00",
img: "/fashion/img/photo29.jpg",
href: "http://zlydnev.ru/fashion/product.php",
slider: "slider_butt slider_butt_2",
class: "box box3"},

{name: "Special watch",
price: "$20.00",
img: "/fashion/img/photo20.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box4"},

{name: "Special watch",
price: "$99.00",
img: "/fashion/img/photo31.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box5"},

{name: "Special watch",
price: "$25.00",
img: "/fashion/img/photo32.jpg",
href: "http://zlydnev.ru/fashion/product.php",
slider: "slider_butt slider_butt_2",
class: "box box6"},

{name: "Special watch",
price: "$75.00",
img: "/fashion/img/photo18.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box7"},

{name: "Special watch",
price: "$85.00",
img: "/fashion/img/photo34.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box8"},

{name: "Special watch",
price: "$55.00",
img: "/fashion/img/photo35.jpg",
href: "http://zlydnev.ru/fashion/product.php",
slider: "slider_butt slider_butt_2",
class: "box box9"},

{name: "Special watch",
price: "$72.00",
img: "/fashion/img/photo25.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box1"},

{name: "Special",
price: "$45.00",
img: "/fashion/img/photo19.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box2"},

{name: "Special watch",
price: "$75.00",
img: "/fashion/img/photo26.jpg",
href: "http://zlydnev.ru/fashion/product.php",
slider: "slider_butt slider_butt_2",
class: "box box3"},

{name: "Special watch",
price: "$20.00",
img: "/fashion/img/photo23.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box4"},

{name: "Special watch",
price: "$99.00",
img: "/fashion/img/photo24.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box5"},

{name: "Special watch",
price: "$25.00",
img: "/fashion/img/photo33.jpg",
href: "http://zlydnev.ru/fashion/product.php",
slider: "slider_butt slider_butt_2",
class: "box box6"},

{name: "Special watch",
price: "$75.00",
img: "/fashion/img/photo22.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box7"},

{name: "Special watch",
price: "$85.00",
img: "/fashion/img/photo30.jpg",
href: "http://zlydnev.ru/fashion/product.php",
class: "box box8"},

{name: "Special watch",
price: "$55.00",
img: "/fashion/img/photo21.jpg",
href: "http://zlydnev.ru/fashion/product.php",
slider: "slider_butt slider_butt_2",
class: "box box9"}
];
